var legendoDon = {
    opener: {
        text: "It is a Friday afternoon when you just get home from school and start getting yourself settled down. On such an eventful day, your own birthday, your dad wasn't even here and your mother, well only her remnants are left now. Knowing it’s your birthday and you’re alone like usual, you put on your shoes, grab your wallet, and head out across the street to the closest convenience store. When you walk out, you have a drink i one hand and a box with a small vanilla cake with strawberry custard in another.You make your way across the street and start walking home.When you get home you grab the small brown coffee table and place it down in front of you while you unwrap the cake box.Feeling a bit lonely, you walk to the restroom to get yourself situated and then head up to the attic to grab a picture of your mother.As you're exploring the attic you see a shiny object in your peripheral vision and decide to check it out.After moving the boxes on top of it out of the way, you see a box with a key hole and a key tied on top of it along with a picture of your grandfather.You decide to bring it down with you and set it at the corner of the table.Putting a candle on top of the cake, you light it and make a wish, as you feel tears rolling down, you start to feel ridiculous crying since this wasn’t the first time this has happened.As you cut the cake and eat a slice, your eyes start to wander back to the box you took down and you decide to open it.Upon opening the box, you put your hand in and you grab what seems to be a locket of your grandmother.A moment later, you start to feel weird, for some odd reason, you seem to be disappearing.As you look at the cake and then back at your hands, you simply smile and accept what’s about to happen.A few hours later you feel your eyes start to open, but you ask yourself how you were watching yourself disappear. A couple minutes later a small creature with wings appears next to you. Mysteriously, she approaches you and starts to communicate with you. Cade, the mentor, asks you whether or not you wish to be admitted into the academy under his instructions?",
        options: [["town", 'Sure, yeah I\'ll follow, but ya know, where are we going first??'], ["freak", 'Are you talking to me!?!, bro what even are you?? How can you talk?'], ["lost", 'Eh, it has no significance whatsoever, just ignore him and move along']]
    },
    town: {
        text:'As you follow the fairy to town, the fairy introduces himself and informs you of the status window. This status window displays your status, strength, health, and helps identify unknown organisms along with objects. You, as well as each avatar, are given a status window that is only seen by yourself. After following the fairy for a while, you guys end up arriving at what seems to be an academy where you are introduced to your mother\'s mentor,Cade. Welcome! User Dante! I am Window, I will help you on your journey to beat [[f̶̛̞̟̼̉̋͌̌̏͑͝O̴̢͎͓͐͛͐ͅr̵͔͓̭̄ᘿᖇᖇᓍᖇ ͔B̷̧̟̊͋̈̏̽̈́̃͆̕ị̵̬̑̔̓̔̐̈́͑͋̇d̸̨͎̯̱̫͇͇̠͈̉̈͌̈͋͛̊͛͝s̸̘̏̆̾̇̒̔̂̉̍͝p̶̪̣͍̯̩̰̲͠E̸̗̼͈̲̘̔̀͑͘ͅḷ̷̨̩̒̈́l̸̹̼̥͎̲̣̏͋̂̃̾͒͛̓̅]] .',
        options: [['']],
    }
    freak: { 
        text:
        option:
    }
};
   
